application: kumoboard
version: 1
runtime: python27
api_version: 1

default_expiration: 7d
threadsafe: true

libraries:
- name: jinja2
  version: latest

handlers:
- url: /static/(.*\.(css|js|jpg|png|gif|exe))
  static_files: static/\1
  upload: static/(.*\.(css|js|jpg|png|gif|exe))
  
- url: /robots.txt
  static_files: static/robots.txt
  upload: static/robots.txt
  
- url: /google9f303401127f9bab.html
  static_files: static/robots.txt
  upload: static/robots.txt
  
- url: /marking.html
  static_files: static/marking.html
  upload: static/marking.html

- url: /favicon.ico
  static_files: static/images/favicon.ico
  upload: static/images/favicon.ico

- url: /stats.*
  script: google.appengine.ext.appstats.ui.app

- url: /.*
  script: kumo.app
  
- url: /kumo/.*
  script: kumo.app
